"use client";
import jsPDF from "jspdf";
import { PayoutPreview } from "./PayoutsTable";

interface PayoutDetailsProps {
  payout: PayoutPreview | null;
}

export function PayoutDetails({ payout }: PayoutDetailsProps) {
  if (!payout) {
    return <div className="empty-payout">💸 Select a payout to view details</div>;
  }

  const handleDownloadReceipt = () => {
    const doc = new jsPDF();

    // === HEADER ===
    doc.setFillColor(230, 100, 0); // brand orange
    doc.rect(0, 0, 210, 30, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(18);
    doc.text("Payout Receipt", 20, 20);

    // === BODY ===
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "normal");
    doc.setFontSize(12);

    let y = 50;
    doc.text(`Receipt ID: #${payout.id}`, 20, y);
    doc.text(`Recipient: ${payout.recipient}`, 20, (y += 10));
    doc.text(`Event: ${payout.event}`, 20, (y += 10));
    doc.text(`Amount: ${payout.amount}`, 20, (y += 10));
    doc.text(`Date: ${payout.date}`, 20, (y += 10));

    // Status with color
    y += 15;
    doc.setFont("helvetica", "bold");
    doc.text("Status:", 20, y);
    doc.setFont("helvetica", "normal");

    if (payout.status === "Completed") {
      doc.setTextColor(0, 150, 0);
    } else if (payout.status === "Pending") {
      doc.setTextColor(255, 165, 0);
    } else {
      doc.setTextColor(200, 0, 0);
    }
    doc.text(payout.status, 50, y);

    // Reset color
    doc.setTextColor(0, 0, 0);

    // === TRANSACTIONS ===
    y += 20;
    doc.setFont("helvetica", "bold");
    doc.text("Transactions:", 20, y);
    doc.setFont("helvetica", "normal");

    payout.transactions.forEach((txn, idx) => {
      doc.text(`• ${txn}`, 30, y + 10 + idx * 10);
    });

    // Footer
    doc.setFontSize(10);
    doc.setTextColor(120, 120, 120);
    doc.text("Generated by Eventify Platform", 20, 290);

    doc.save(`receipt-${payout.id}.pdf`);
  };

  return (
    <div className="payout-details">
      <h3>Payout Details</h3>
      <p><strong>Recipient:</strong> {payout.recipient}</p>
      <p><strong>Event:</strong> {payout.event}</p>
      <p><strong>Amount:</strong> {payout.amount}</p>
      <p><strong>Date:</strong> {payout.date}</p>
      <p><strong>Status:</strong> {payout.status}</p>

      <h4>Transactions</h4>
      <ul>
        {payout.transactions.map((txn, i) => (
          <li key={i}>{txn}</li>
        ))}
      </ul>

      <button className="download-btn" onClick={handleDownloadReceipt}>
        📄 Download Receipt
      </button>
    </div>
  );
}
